name: taxi_native
description: "A new Flutter project."

version: 1.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  http: ^1.2.1
  json_store: ^2.0.1
  shared_preferences: ^2.2.2
  sqflite_common_ffi: ^2.3.3
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  mobx: ^2.3.3+1
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  cached_network_image: ^3.3.1
  skeletonizer: ^1.3.0
  context_menus: ^2.0.0+1
  # audio_service:
  #   git:
  #     url: https://github.com/mcMineyC/audio_service.git
  #     ref: minor
  #     path: audio_service
  audio_service_mpris: ^0.1.4
  # audioplayers:
  #   path: ../audioplayers/packages/audioplayers
  beamer: ^1.6.1
  youtube_explode_dart: ^2.3.6
  socket_io_client: ^2.0.3+1
  easy_debounce: 2.0.3
  # flutter_lints: ^4.0.0
  riverpod_generator: ^2.4.0
  custom_lint: ^0.7.0
  json_serializable: ^6.8.0
  device_info_plus: ^10.1.0
  provider: ^6.1.2
  flex_color_picker: ^3.5.1
  just_audio: 
    git:
      url: https://github.com/mcMineyC/just_audio.git
      path: just_audio
      ref: minor
  just_audio_media_kit: 2.0.3
  just_audio_windows: any
  media_kit_libs_linux: any
  # media_kit_libs_windows: any
  just_audio_background: any
  media_kit_native_event_loop: ^1.0.8
  rxdart: ^0.28.0
  just_audio_web: ^0.4.11
  squiggly_slider: ^1.0.5
  dynamic_color: ^1.7.0
  media_kit_libs_windows_audio: any
  build_runner: ^2.4.14
  hooks_riverpod: ^2.6.1
  url_launcher: ^6.3.1
  #analyzer: ^0.38.2
  # just_audio_handlers:
  #   # git:
  #   #   url: https://github.com/mcMineyC/just_audio_handlers.git
  #   path: ../just_audio_handlers
dev_dependencies:
  build_runner:
  custom_lint:
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3

flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
          style: normal
