name: Flutter Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '21'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable # or: beta, master (or main)

      - run: sudo apt-get update
      - run: sudo apt-get install libunwind-dev zip
      - run: sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev
      - run: sudo apt install libmpv-dev mpv
      - run: flutter clean
      - run: flutter pub get
#      - run: flutter format --set-exit-if-changed .
      - run: dart run build_runner build --delete-conflicting-outputs
      - run: flutter build apk
      - run: flutter build linux
      - run: sh -c "cd build/linux/x64/release/bundle && zip -r taxi-native-linux_x64.zip . && cp taxi-native-linux_x64.zip ../../../../../"
      - run: cp build/app/outputs/apk/release/app-release.apk taxi-native.apk

      - name: Check if taxi.exe exists
        id: check_file
        run: |
          if [ -f Installers/taxi.exe ]; then
            echo "file_exists=true" >> $GITHUB_ENV
          else
            echo "file_exists=false" >> $GITHUB_ENV
          fi

      - uses: ncipollo/release-action@v1
        if: env.file_exists == 'true'
        with:
          artifacts: "taxi-native.apk,taxi-native-linux_x64.zip,Installers/taxi.exe"
          tag: ${{ steps.vars.outputs.sha_short }}
          makeLatest: true
          name: ${{ steps.date.outputs.date }}
          body: "## This was autoreleased via github actions"

      - uses: ncipollo/release-action@v1
        if: env.file_exists == 'false'
        with:
          artifacts: "taxi-native.apk,taxi-native-linux_x64.zip"
          tag: ${{ steps.vars.outputs.sha_short }}
          makeLatest: true
          name: ${{ steps.date.outputs.date }}
          body: "## This was autoreleased via github actions"

      - uses: actions/upload-artifact@v2
        with:
          name: release-apk.apk
          path: ./taxi-native.apk

      - uses: actions/upload-artifact@v2
        with:
          name: release-linux.zip
          path: ./taxi-native-linux_x64.zip

      - uses: actions/upload-artifact@v2
        if: env.file_exists == 'true'
        with:
          name: taxi.exe
          path: Installers/taxi.exe