name: Flutter CI

on:
  push:
    branches:
      - main
permissions:
  contents: write 

jobs:
  setup:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d %I:%M')">> $GITHUB_ENV
      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      # - name: Set up Flutter
      #   uses: subosito/flutter-action@v2
      #   with:
      #     channel: stable # or: beta, master (or main)
      # - name: Prep project
      #   run: |
      #     flutter clean
      #     flutter pub get
      #     dart run build_runner build --delete-conflicting-outputs
      - name: Set default value for windows build
        run: echo "file_exists=false" >> $GITHUB_ENV
  build-android:
    runs-on: ubuntu-22.04
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable # or: beta, master (or main)
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '21'
      - run: flutter build apk
      - run: cp build/app/outputs/apk/release/app-release.apk taxi-native.apk
      - uses: actions/upload-artifact@v3
        with:
          name: taxi-native.apk
          path: taxi-native.apk
  build-linux:
    runs-on: ubuntu-22.04
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable # or: beta, master (or main)
      - name: Install dependencies
        run: |
          sudo apt-get install libunwind-dev zip
          sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev
          sudo apt install libmpv-dev mpv
      - run: flutter build linux
      - run: sh -c "cd build/linux/x64/release/bundle && zip -r taxi-native-linux_x64.zip . && cp taxi-native-linux_x64.zip ../../../../../"
      - uses: actions/upload-artifact@v3
        with:
          name: taxi-native-linux_x64.zip
          path: taxi-native-linux_x64.zip
  build-windows-test:
    runs-on: windows-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter build windows
      - name: Compile .ISS to .EXE Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: Installers/innoSetupScript.iss
          options: /O+
      - run: cp build/windows/runner/Release/taxi.exe Installers/taxi.exe
      - uses: actions/upload-artifact@v3
        with:
          name: taxi.exe
          path: Installers/taxi.exe
      - run: echo "file_exists=true" >> $GITHUB_ENV
  build-windows:
    needs: setup
    runs-on: ubuntu-22.04
    steps:
      - name: Check if taxi.exe exists
        id: check_file
        run: |
          if [ -f Installers/taxi.exe ]; then
            echo "file_exists=true" >> $GITHUB_ENV
          else
            echo "file_exists=false" >> $GITHUB_ENV
          fi
      - run: echo $file_exists
      - uses: actions/upload-artifact@v3
        if: env.file_exists == 'true'
        with:
          name: taxi.exe
          path: Installers/taxi.exe
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter build macos
      - run: cp build/macos/Build/Products/Release/taxi.app taxi.app
      - uses: actions/upload-artifact@v3
        with:
          name: taxi.app
          path: taxi.app
  release:
    runs-on: ubuntu-22.04
    needs: [build-android, build-linux, build-windows] 
    steps:
      - uses: actions/checkout@v4
      - uses: ncipollo/release-action@v1
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: taxi-native.apk
          path: .
      - uses: actions/download-artifact@v3
        with:
          name: taxi-native-linux_x64.zip
          path: .
      - uses: ncipollo/release-action@v1
        if: env.file_exists == 'true'
        with:
          artifacts: "taxi-native.apk,taxi-native-linux_x64.zip,Installers/taxi.exe"
          tag: ${{ env.sha_short }}
          makeLatest: true
          name: ${{ steps.date.outputs.date }}
          body: "## This was autoreleased via github actions"
      - uses: ncipollo/release-action@v1
        if: env.file_exists == 'false'
        with:
          artifacts: "taxi-native.apk,taxi-native-linux_x64.zip"
          tag: ${{ env.sha_short }}
          makeLatest: true
          name: ${{ env.date }}
          body: "## This was autoreleased via github actions"
      - uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3
        with:
          name: release-apk.apk
          path: ./taxi-native.apk
      - uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3
        with:
          name: release-linux.zip
          path: ./taxi-native-linux_x64.zip
      - uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 
        if: env.file_exists == 'true'
        with:
          name: taxi.exe
          path: Installers/taxi.exe
