name: Flutter CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '21'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - run: sudo apt-get update
      - run: sudo apt-get install libunwind-dev
      - run: sudo apt-get install libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev
      - run: flutter pub get
#      - run: flutter format --set-exit-if-changed .
      - run: dart run build_runner build
      - run: flutter build apk
#      - run: flutter build linux
      - uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk
